<html>
    
    <head>
        <meta charset="UTF-8">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script type="text/javascript" src="/js/app.js"></script>
    </head>
    
    
    <body>
        
        <form action="" method="POST">
            <label>Логин: </label>
            <input name="name" type="text" value="" /> <br>
            <label>Пароль: </label>
            <input name="password" type="password" value="" /> <br>
            <input type="submit" value="Логин" /> <br>
        </form>
    </body>
</html>